# Generated by Django 4.2.8 on 2026-06-21 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CollegeActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('activity_type', models.CharField(choices=[('Event', 'Event'), ('Announcement', 'Announcement'), ('Notice', 'Notice'), ('Holiday', 'Holiday'), ('Deadline', 'Deadline')], max_length=255)),
                ('description', models.TextField()),
                ('activity_date', models.DateField()),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='activities/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'College Activities',
                'ordering': ['-activity_date'],
            },
        ),
    ]
