# Generated by Django 4.2.8 on 2026-02-15 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_customuser_date_of_birth_customuser_gender_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='category',
            field=models.CharField(choices=[('notes', 'Notes'), ('assignment', 'Assignment'), ('lab', 'Lab File'), ('pyq', 'PYQ'), ('roadmap', 'Roadmap'), ('whatsapp', 'Whatsapp Community'), ('official', 'Official Links'), ('cs3f', 'CS 3F'), ('telegram', 'Telegram Premium'), ('holiday', 'Holiday')], max_length=30),
        ),
    ]
