# Generated by Django 4.2.8 on 2026-06-21 04:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('Notes', 'Notes'), ('Assignments', 'Assignments'), ('Lab Files', 'Lab Files'), ('Previous Year Papers', 'Previous Year Papers'), ('Roadmaps', 'Roadmaps'), ('WhatsApp Groups', 'WhatsApp Groups'), ('Official Resources', 'Official Resources'), ('CS3F', 'CS3F'), ('Telegram Groups', 'Telegram Groups'), ('Holiday Homework', 'Holiday Homework')], max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='resources/')),
                ('external_link', models.URLField(blank=True, max_length=500, null=True)),
                ('downloads', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bookmarks', models.ManyToManyField(blank=True, related_name='bookmarked_resources', to=settings.AUTH_USER_MODEL)),
                ('likes', models.ManyToManyField(blank=True, related_name='liked_resources', to=settings.AUTH_USER_MODEL)),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_resources', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
